client_id = "a49b088e864543360fe069daa265c3d5"
name = "Ali商品リライト誉"
handle = "ds-rewrite-app-homare"
application_url = "https://ds-rewrite-app-3.vercel.app"
embedded = true

[auth]
redirect_urls = [
  "https://ds-rewrite-app-3.vercel.app/auth/callback",
  "https://ds-rewrite-app-3.vercel.app/auth/shopify/callback",
  "https://ds-rewrite-app-3.vercel.app/api/auth/callback"
]

[access_scopes]
scopes = "read_products,write_products"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[[additional_pages]]
handle = "products-list"
url = "/app/products/list"
name = "商品リスト"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
